CREATE DATABASE IF NOT EXISTS desafioats;
CREATE USER 'desafio'@'%' IDENTIFIED BY 'testE%40123X';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON desafioats.* TO 'desafio'@'%';
FLUSH PRIVILEGES;